# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json


{
  "email": "zholud@gmail.com",
  "username": "Artem Zholud",
  "status": "pro",
  "password": "123456789"
}

###


## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "zholud@gmail.com",
  "password": "123456789"
}

###

## Проверка состояния пользователя.


GET  http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inpob2x1ZEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkFydGVtIFpob2x1ZCIsImlkIjoiNjVlMGMxMThhMDk1OWM1MDQ0MmZmMDY1IiwiaWF0IjoxNzA5MjMxODMzLCJleHAiOjE3MDk0MDQ2MzN9.6iO2I5hGtHZkVN0R7CUgSoIiZ4_S-0KkVU8CRx5_JSQ

###

## Отправить изображение

POST http://localhost:5000/users/65cbd3f22bafc2e35c2fe2e5/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\artem\Desktop\projects\1695089-six-cities-6\markup\img\avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
